"""Amend password field with hash, remove confirm password field

Revision ID: 447c33682c41
Revises:
Create Date: 2023-09-12 07:04:50.491614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447c33682c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'user_password', sa.String(length=50), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'confirm_password', sa.VARCHAR(
                length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column(
            'password', sa.VARCHAR(
                length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('user_password')

    # ### end Alembic commands ###
