"""Add clubs_id back into Users table

Revision ID: 56787535d6d6
Revises: a01811db2fcb
Create Date: 2023-09-22 06:10:35.880314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56787535d6d6'
down_revision = 'a01811db2fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clubs', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
