"""Amend training days to accept array input

Revision ID: e1d71b363fb3
Revises: 56787535d6d6
Create Date: 2023-10-04 16:47:23.845688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d71b363fb3'
down_revision = '56787535d6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('days_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('teams_days_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_foreign_key('teams_days_id_fkey', 'days', ['days_id'], ['id'])
        batch_op.alter_column('days_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
